In [1]:
#This app scrape product data from amazon website

#BeautifulSoup4
#requests
#lxml

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
url = "https://www.amazon.com/Apple-Wireless-Bluetooth-Headphones-Cancellation/dp/B0DLY219Q7/ref=sr_1_1?crid=8GS7K5IQAY7F&dib=eyJ2IjoiMSJ9.kfVqMPQ2rgZ39R6D_N9MHp6f7v_6fFevbeBpB-bJgISk_X6EhtyziQ3pbfKSzgTWPzsk9909Rxp4XSHfK69VJNL2w5zT-fGFfNsGHEQjm8ZkFJaCElyFjTnvVTc3GPdRUHk8UiBnC3Axc7Nl33bIR4YIiAZvul8tUo9xI__FSGA4X3DoHc8iReawYNafn6wEitdKP0D10zDabERDZoTzMqHGHEB04m7u3tpymgJsdA8.PKyU9yVF08kqMGiXkduSG01s3rAUdu8TB5aq9M_lRrc&dib_tag=se&keywords=apple+airpods&qid=1782373569&sprefix=appl%2Caps%2C501&sr=8-1"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9"
}
response = requests.get(url, headers=headers)
if response.status_code == 200:
    print("response.status_code")
else: 
    print("fetching rrror", response.status_code)

response.status_code

In [4]:
soup = BeautifulSoup(response.content, "html.parser")
print(soup.title.text)

Amazon.com: Apple AirPods 4 Wireless Earbuds, Bluetooth Headphones, with Active Noise Cancellation (Renewed) : Electronics

In [5]:
title = soup.find("span", id="productTitle")
if title:
    title = title.get_text(strip=True)
    print(title)
else:
    print("Title Not Fount")

Apple AirPods 4 Wireless Earbuds, Bluetooth Headphones, with Active Noise Cancellation (Renewed)

In [6]:
price = soup.find("span", class_="a-price-whole")
if price:
    price = price.get_text(strip=True)
    print(price)
else:
    print("price not found")

6,952.

In [7]:
rating = soup.find("span", class_="a-icon-alt")
if rating:
    rating = rating.get_text(strip=True)
    print(rating)
else:
    print("rating not found")

4.4 out of 5 stars

In [8]:
reviews = soup.find("span", id="acrCustomerReviewText")
if reviews:
    reviews = reviews.get_text(strip=True)
    print(reviews)
else:
    print("reviews not found")

(714)

In [9]:
availability = soup.find("div", id="availability")
if reviews:
    availability = availability.get_text(strip=True)
    print(availability)
else:
    print("reviews not found")

This item cannot be shipped to your selected delivery location. Please choose a different delivery location.

In [10]:
brand = soup.find("a", id="bylineInfo")
if brand:
    brand = brand.get_text(strip=True)
    print(brand)
else:
    print("brand not found")

Visit the Amazon Renewed Store

In [11]:
image = soup.find("img", id="landingImage")
if image:
    print(image.get("src"))
else:
    print("image not found")

https://m.media-amazon.com/images/I/41JfdFBHleL._AC_SY300_SX300_QL70_ML2_.jpg

In [12]:
data = {
    "Product Name" : [title],
    "Price" : [price],
    "Rating" : [rating],
    "Reviews" : [reviews],
    "Availability" : [availability],
    "Brand" : [brand],
    "ImageURL" : [image.get("src")]
}
df = pd.DataFrame(data)
df

,Product Name,Price,Rating,Reviews,Availability,Brand,ImageURL
0,"Apple AirPods 4 Wireless Earbuds, Bluetooth He...","6,952.",4.4 out of 5 stars,(714),This item cannot be shipped to your selected d...,Visit the Amazon Renewed Store,https://m.media-amazon.com/images/I/41JfdFBHle...

In [13]:
df.to_csv("/Users/war/Downloads/amazon_products.csv", index=False)
print("load successfully")

load successfully

In [18]:
df.to_excel("/Users/war/Downloads/amazon_products.xlsx", index=False)
print("load successfully")

load successfully

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  1 non-null      str
 1   Price         1 non-null      str
 2   Rating        1 non-null      str
 3   Reviews       1 non-null      str
 4   Availability  1 non-null      str
 5   Brand         1 non-null      str
 6   ImageURL      1 non-null      str
dtypes: str(7)
memory usage: 188.0 bytes

In [21]:
df["Price"] = df["Price"].str.replace(",","")
df["Price"] = df["Price"].astype(float)
df

,Product Name,Price,Rating,Reviews,Availability,Brand,ImageURL
0,"Apple AirPods 4 Wireless Earbuds, Bluetooth He...",6952.0,4.4 out of 5 stars,(714),This item cannot be shipped to your selected d...,Visit the Amazon Renewed Store,https://m.media-amazon.com/images/I/41JfdFBHle...

In [24]:
print(df.dtypes)

Product Name        str
Price           float64
Rating          float64
Reviews             str
Availability        str
Brand               str
ImageURL            str
dtype: object

In [26]:
df["Rating"] = df["Rating"].astype(str)
df["Rating"] = df["Rating"].str.extract(r'(\d+\.\d+)')
df["Rating"] = df["Rating"].astype(float)

In [27]:
df["Reviews"] = df["Reviews"].str.replace("(", "", regex=False)
df["Reviews"] = df["Reviews"].str.replace(")", "", regex=False)
df["Reviews"] = df["Reviews"].str.replace(",", "", regex=False)
df["Reviews"] = df["Reviews"].astype(int)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  1 non-null      str
 1   Price         1 non-null      float64
 2   Rating        1 non-null      float64
 3   Reviews       1 non-null      int64
 4   Availability  1 non-null      str
 5   Brand         1 non-null      str
 6   ImageURL      1 non-null      str
dtypes: float64(2), int64(1), str(4)
memory usage: 188.0 bytes

In [ ]:
import shutil

shutil.copy("Online_Retail_Cleaning.ipynb", r"C:\Users\war\Downloads\Online_Retail_Cleaning.ipynb")